// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {json} from '../models';

export function AddDownload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddURL(arg1:string):Promise<string>;

export function DeleteDownload(arg1:string):Promise<void>;

export function GetDownloadStatus(arg1:string):Promise<main.DownloadItem>;

export function GetHistory():Promise<Array<json.RawMessage>>;

export function GetIconMode():Promise<string>;

export function GetStartupEnabled():Promise<boolean>;

export function IsServerRunning():Promise<boolean>;

export function ListDownloads():Promise<Array<main.DownloadItem>>;

export function OpenDirectoryDialog():Promise<string>;

export function PauseDownload(arg1:string):Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function SetIconMode(arg1:string):Promise<void>;

export function SetStartupEnabled(arg1:boolean):Promise<void>;
