// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddDownload'](arg1, arg2, arg3);
}

export function AddURL(arg1) {
  return window['go']['main']['App']['AddURL'](arg1);
}

export function DeleteDownload(arg1) {
  return window['go']['main']['App']['DeleteDownload'](arg1);
}

export function GetDownloadStatus(arg1) {
  return window['go']['main']['App']['GetDownloadStatus'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetIconMode() {
  return window['go']['main']['App']['GetIconMode']();
}

export function GetStartupEnabled() {
  return window['go']['main']['App']['GetStartupEnabled']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsServerRunning() {
  return window['go']['main']['App']['IsServerRunning']();
}

export function ListDownloads() {
  return window['go']['main']['App']['ListDownloads']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SetIconMode(arg1) {
  return window['go']['main']['App']['SetIconMode'](arg1);
}

export function SetStartupEnabled(arg1) {
  return window['go']['main']['App']['SetStartupEnabled'](arg1);
}
